server:
  port: 3270

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.8.52/JWT
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.jwt_security.mapper

  configuration:
    map-underscore-to-camel-case: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 5000000
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"